### ISSUE TITLE
HMM build phrases 

### ISSUE THREAD

**Issue by ellLazar** [chriscore/MarkovSharp#2]
support,
about your example o language "understanding"
how to build vocabulary on other language, 
how to construct the model learning+ implementing ?

any code example, or link will be appreciated

**Comment by chriscore** [comment]
Hi ellLazar

I assume that we are talking about the StringMarkov example implementation here; the library is agnostic to the language of text that it is trained on, so nothing different should need to be done to build a model for other languages, just change the text data that is provided for training. 

No implementation should be necessary, just replace the three lines of example text training data with something more realistic that suits you, perhaps a full essay or book split by full stops for example?

This example is taken from readme.md:

	// This simulates a small amount of training data
	var lines = new string[]
	{
		"Frankly, my dear, I don't give a damn.",
		"Mama always said life was like a box of chocolates. You never know what you're gonna get.",
		"Many wealthy people are little more than janitors of their possessions."
	};

	// Create a new model
	var model = new StringMarkov(1);

	// Train the model using the training data
	model.Learn(lines);

	// Create permutations using the model
	Console.WriteLine(model.Walk().First());

	// Output example:
	// Frankly, my dear, I don't give a box of their possessions.

**Comment by ellLazar** [comment]
stringMarkov

hello Chris, thanks for answer.
I want to understand your model, in human words:
1.
first I enter all available sentences text(more or less) I will be used
this is the "learning"
2. 
now, on 'given sentence', I enter this text to model,
and getting the "best" sentences that fit the 'given sentence' ?
but give understandable meanings to 'given sentence' ?

is it correct ?

**Comment by chriscore** [comment]
Hi

I think maybe there is a little misunderstanding here about what the Markov model is producing. 

This is a quick explanation of what the Markov model implemented is doing, which I have quoted from Jeff Atwood at https://blog.codinghorror.com/markov-and-you/

> A generator can make more interesting text by making each letter a random function of its predecessor. We could, therefore, read a sample text and count how many times every letter follows an A, how many times they follow a B, and so on for each letter of the alphabet. When we write the random text, we produce the next letter as a random function of the current letter. The Order-1 text was made by exactly this scheme:
>
> t I amy, vin. id wht omanly heay atuss n macon aresethe hired boutwhe t, tl, ad torurest t plur I wit hengamind tarer-plarody thishand.
>
> We can extend this idea to longer sequences of letters. The order-2 text was made by generating each letter as a function of the two letters preceding it (a letter pair is often called a digram). The digram TH, for instance, is often followed in English by the vowels A, E, I, O, U and Y, less frequently by R and W, and rarely by other letters.
> 
> Ther I the heingoind of-pleat, blur it dwere wing waske hat trooss. Yout lar on wassing, an sit." "Yould," "I that vide was nots ther.
>
> The order-3 text is built by choosing the next letter as a function of the three previous letters (a trigram).
> 
> I has them the saw the secorrow. And wintails on my my ent, thinks, fore voyager lanated the been elsed helder was of him a very free bottlemarkable,
>
> By the time we get to the order-4 text, most words are English, and you might not be surprised to learn that it was generated from a Sherlock Holmes story ( "The Adventure of Abbey Grange'').
> 
> His heard." "Exactly he very glad trouble, and by Hopkins! That it on of the who difficentralia. He rushed likely?" "Blood night that.


So the Markov model is not providing us any inherent understanding of the meaning of the words which make up a sentence, but is able to predict that given we have a certain historical state (for example, a few words already written), what are the possible options and probabilities of the next word to come.

MarkovSharp supports making a call to predict what the next state might be, given a current state 'seed'.
An example of how to do this is given below:

```
        // create a model
        StringMarkov model = new StringMarkov(1);

        // train the model
	model.Learn(new List<string>()
	{
		"this is a good example of how a markov model works",
		"hopefully this is an extremely useful introduction to learning about markov models and data prediction",
		"is this going to be a good idea or a bad idea"
	});
	
        // get possible next states, given a current state of 'this is'
	var nextStates = model.GetMatches("this is");
```

Hopefully that helps.

Chris
