### ISSUE TITLE
MarkovSharp Namespace Unavailable?

### ISSUE THREAD

**Issue by Headline** [chriscore/MarkovSharp#3]
Installed MarkovSharp using nuget. The only version where the namespace MarkovSharp exists is in version 1.0, but doesn't contain TokenisationStrategies folder either.

Not sure if this is my error, but MarkovSharp is definitely added to my project (v2.1.24)

```
The type or namespace name 'TokenisationStrategies' does not exist in the namespace 'MarkovSharp' (are you missing an assembly reference?)
```

**Comment by Headline22** [comment]
I've built it myself and added the reference to the .dll manually. It seems this works fine. Perhaps something is messed up with nuget?

**Comment by chriscore** [comment]
Hi, thanks.

Yeah that doesn't sound right at all! I'll look into sorting it, thanks for bringing it up.

Chris
